name: CICD using Maven and Jenkins
on: 
  workflow_dispatch:
jobs:
  CICDJob:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo on ubuntu server
        uses: actions/checkout@v4
      - name: Install Java and Maven on ubuntu server
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build the source code and generate .war file  
        run: mvn package
      - name: Get the artifact and upload on github repo
        uses: actions/upload-artifact@v4
        with:
         name: java-example-artifact
         path: /home/runner/work/MavenBuild-SL/MavenBuild-SL/target/java-example.war
      - name: Connect to LAB and run curl command to trigger a Job 
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with: 
          host: '3.110.180.217' # change to your lab server public IP
          user: 'labuser'
          pass: 'Nuvelabs123$'
          port: 22
          connect_timeout: 10s
          first_ssh: |
             sudo chmod 777 /var/lib/tomcat9/webapps
          scp: |
             './target/*war' => /var/lib/tomcat9/webapps
          last_ssh: |
             sudo systemctl restart tomcat9

          
      
      

     
